// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIH-UFLmqCb3DWa5566bEqPxYTfbVtXpU',
    appId: '1:443653754124:web:e3341bf09d831171388d29',
    messagingSenderId: '443653754124',
    projectId: 'camp-app-41299',
    authDomain: 'camp-app-41299.firebaseapp.com',
    databaseURL: 'https://camp-app-41299-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camp-app-41299.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzVw3HxmkWlddoiaLsjBn3TVs-hy6TEZ8',
    appId: '1:443653754124:android:28977832a2ea39eb388d29',
    messagingSenderId: '443653754124',
    projectId: 'camp-app-41299',
    databaseURL: 'https://camp-app-41299-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camp-app-41299.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvV2Pwfu5pkQDnRGIaB9laAWj6U0_AoAk',
    appId: '1:443653754124:ios:ccea89b4d84d0ebf388d29',
    messagingSenderId: '443653754124',
    projectId: 'camp-app-41299',
    databaseURL: 'https://camp-app-41299-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camp-app-41299.appspot.com',
    iosClientId: '443653754124-dlb3vbkobe018chlb5cl9v55u3nkgi2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.campTrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvV2Pwfu5pkQDnRGIaB9laAWj6U0_AoAk',
    appId: '1:443653754124:ios:ccea89b4d84d0ebf388d29',
    messagingSenderId: '443653754124',
    projectId: 'camp-app-41299',
    databaseURL: 'https://camp-app-41299-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'camp-app-41299.appspot.com',
    iosClientId: '443653754124-dlb3vbkobe018chlb5cl9v55u3nkgi2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.campTrip',
  );
}
